### ISSUE TITLE
Cached pages and overwritten headers

### ISSUE THREAD

**Issue by jlecour** [sparklemotion/mechanize#428]
Hi,

I'm using Mechanize for automated tests, to verify that a web server has the intended behaviour regarding cache policy.

When Mechanize use its cache, on a subsequent request for a previously visited page, it returns the cached `page` object, with its headers and never shows the headers returned by the server.

Here is very basic example

```ruby
agent = Mechanize.new
url = "https://en.wikipedia.org/wiki/Main_Page"
page1 = agent.get(url)
assert_equal "200", page1.code
page2 = agent.get(url)
assert_equal "304", page2.code
```

The `page1` and `page2` objects are the same ; not only their value but there identity.

I can see in the log that the 2nd request returns a `304 Not Modified` status, but I can't find a way to verify that with the `agent` or `page` objects since `page.code` returns the first `200 OK` status.

Thanks for any help.

**Comment by leejarvis** [comment]
The idea is that you shouldn't need to verify that. If Mechanize see's the `304` response status it knows that the response is the same, so it returns the previous page object:

https://github.com/sparklemotion/mechanize/blob/master/lib/mechanize/http/agent.rb#L304-L306

You could disable history, but that means the second response would be a 200 still since Mechanize wouldn't send an `If-Modified-Since` header.

If you just want to verify the response non-programatically you can check the log output.
