### ISSUE TITLE
follow_meta_refresh does not handle infinite refresh cycles

### ISSUE THREAD

**Issue by postmodern** [sparklemotion/mechanize#429]
I ran into this issue when visiting `http://www.wunderground.com/` with `agent.follow_meta_refresh = true`. The index page contains the following meta refresh:

```
<meta http-equiv="Refresh" content="330;URL=/?MR=1" />
```

Following that refresh, the `/?MR=1` page contains the following meta refresh:

```
<meta http-equiv="Refresh" content="330;URL=" />
```

This causes an infinite refresh cycle. Setting `agent.follow_meta_refresh_self = false` does not prevent the cycle. Setting `agent.redirection_limit = 2` also does not prevent the cycle. It seems like `Mechanize::HTTP::Agent` should maintain a separate history stack for redirections, in order to determine when we've hit a cyclical redirect.

**Comment by flavorjones** [comment]
See #523; I don't think this is an infinite loop, merely a really long one because this refresh happens after 330 seconds. That is, `Mechanize::HTTP::Agent` sleeps for 330 seconds before proceeding.

If that seems silly, well, yeah, it seems silly to me, too -- but that sleep logic has been present since 6545d6a in 2008, so since Mechanize 0.8.5.

Hope this helps. And apologies for the length of time without a reply.
