### ISSUE TITLE
switch to Typhoeus

### ISSUE THREAD

**Issue by acrogenesis** [sparklemotion/mechanize#478]
Are you willing to switch to Typhoeus instead of Net::Http, I'm looking into doing this if you're interested I can make the PR when it's done.

**Comment by drbrain** [comment]
What would be the benefits?  libcurl isn't significantly faster than Net::HTTP, and isn't familiar to the maintainers.  Switching could add many bugs that we'd need to deal with for some time.

**Comment by knu** [comment]
What about Mechanize support Faraday instead?  There are many HTTP backends out there and a single backend cannot fill the needs of every user and occasion anyway.

**Comment by leejarvis** [comment]
I think supporting Faraday and defaulting to Net::HTTP would be a nice compromise. However, I believe it'll be a fair amount of work. That said, Mechanize doesn't really expose the mechanics of the HTTP library by design; so I'm not really sure what we gain. Why do you want to use Typoeus instead of Net::HTTP, @acrogenesis?
