### ISSUE TITLE
mechanize v2.7.6 socksify patch no working

### ISSUE THREAD

**Issue by groverz** [sparklemotion/mechanize#535]
mechanize v2.7.6 socksify patch no working, mechanize v2.7.5 working.

```
require "socksify"
require 'socksify/http'

Socksify::debug = true

class Mechanize::HTTP::Agent
  public
  def set_socks addr, port
    set_http unless @http
    class << @http
      attr_accessor :socks_addr, :socks_port

      def http_class
        Net::HTTP.SOCKSProxy(socks_addr, socks_port)
      end
    end

    @http.socks_addr = addr
    @http.socks_port = port
  end
end
```

**Comment by MatzFan** [comment]
I don't now what the upstream problem is, but it is definitely a problem with using the `net-http-persistent` gem v3.0.0, perhaps you installed this with mechanize v2.7.6.

The socksify patch works fine for me with mechanize v2.7.6 if I lock net-http-persistent to < 3 in my Gemfile. Make sure you use `require 'bundler/setup'` otherwise your app may find v3.0.0 at runtime of course.
